"""Serialize CompileState to a v6 progs.dat, and compute the progdefs CRC.

Ports qcc.c WriteData / PR_WriteProgdefs / CRC_*. Lump order on disk: header,
strings, statements, functions, globaldefs, fielddefs, globals. All fields are
little-endian. The CRC is a CCITT/XMODEM 16-bit CRC over the generated
progdefs.h TEXT (must reproduce 5927 for standard Quake)."""

import struct
from .types import (ev_string, ev_float, ev_vector, ev_field, ev_function)

PROG_VERSION = 6
DEF_SAVEGLOBAL = 1 << 15
RESERVED_OFS = 28

_S_HEADER = struct.Struct("<2i 12i i")
_S_STATEMENT = struct.Struct("<Hhhh")
_S_DEF = struct.Struct("<HHi")
_S_FUNCTION = struct.Struct("<7i8B")

# --- CRC (qcc.c CRC_*: CCITT poly 0x1021, init 0xffff, no reflect, xor 0) ---
def _crc_table():
    tab = []
    for i in range(256):
        v = i << 8
        for _ in range(8):
            v = ((v << 1) ^ 0x1021) if (v & 0x8000) else (v << 1)
            v &= 0xffff
        tab.append(v)
    return tab


_CRCTAB = _crc_table()


def _crc_bytes(data):
    crc = 0xffff
    for byte in data:
        crc = ((crc << 8) & 0xffff) ^ _CRCTAB[((crc >> 8) ^ byte) & 0xff]
    return crc



def progdefs_text(state):
    """Reproduce PR_WriteProgdefs' generated file text, char-for-char."""
    out = []
    out.append("\n/* file generated by qcc, do not modify */\n\ntypedef struct\n"
               "{\tint\tpad[%i];\n" % RESERVED_OFS)
    defs = state.defs
    i = 0
    # globals until end_sys_globals
    while i < len(defs):
        d = defs[i]
        if d.name == "end_sys_globals":
            break
        et = d.type.type
        if et == ev_vector:
            out.append("\tvec3_t\t%s;\n" % d.name)
            i += 3                         # skip _x/_y/_z element defs
        elif et == ev_float:
            out.append("\tfloat\t%s;\n" % d.name)
        elif et == ev_string:
            out.append("\tstring_t\t%s;\n" % d.name)
        elif et == ev_function:
            out.append("\tfunc_t\t%s;\n" % d.name)
        else:
            out.append("\tint\t%s;\n" % d.name)
        i += 1
    out.append("} globalvars_t;\n\n")
    # fields until end_sys_fields
    out.append("typedef struct\n{\n")
    i = 0
    while i < len(defs):
        d = defs[i]
        if d.name == "end_sys_fields":
            break
        if d.type.type != ev_field:
            i += 1
            continue
        at = d.type.aux_type.type
        if at == ev_vector:
            out.append("\tvec3_t\t%s;\n" % d.name)
            i += 3
        elif at == ev_float:
            out.append("\tfloat\t%s;\n" % d.name)
        elif at == ev_string:
            out.append("\tstring_t\t%s;\n" % d.name)
        elif at == ev_function:
            out.append("\tfunc_t\t%s;\n" % d.name)
        else:
            out.append("\tint\t%s;\n" % d.name)
        i += 1
    out.append("} entvars_t;\n\n")
    return "".join(out)


def progdefs_crc(state):
    return _crc_bytes(progdefs_text(state).encode("latin-1"))


def _build_defs(state):
    """globaldefs + fielddefs (qcc.c WriteData def walk). Index 0 is reserved."""
    globaldefs = [(0, 0, 0)]            # zero sentinel
    fielddefs = [(0, 0, 0)]
    for d in state.defs:
        et = d.type.type
        if et == ev_field:
            fielddefs.append((d.type.aux_type.type, state.gi(d.ofs),
                              state.copy_string(d.name)))
        dtype = et
        if (not d.initialized and et != ev_function and et != ev_field
                and d.scope is None):
            dtype |= DEF_SAVEGLOBAL
        globaldefs.append((dtype, d.ofs, state.copy_string(d.name)))
    return globaldefs, fielddefs


def write_progs(state):
    crc = progdefs_crc(state)
    # NOTE: _build_defs appends def names to the string blob AFTER all source
    # strings, exactly as WriteData does its CopyString calls during the walk.
    globaldefs, fielddefs = _build_defs(state)

    # pad strings to 4 bytes (qcc.c: strofs = (strofs+3)&~3)
    strings = bytearray(state.strings)
    while len(strings) % 4:
        strings.append(0)

    parts = []
    header = bytearray(_S_HEADER.size)
    parts.append(header)
    ofs = len(header)

    def emit(blob):
        nonlocal ofs
        start = ofs
        parts.append(blob)
        ofs += len(blob)
        return start

    ofs_strings = emit(bytes(strings))
    stmt = bytearray()
    for (op, a, b, c) in state.statements:
        stmt += _S_STATEMENT.pack(op & 0xffff, a, b, c)
    ofs_statements = emit(stmt)

    fns = bytearray()
    for fn in state.functions:
        if fn is None:                          # index 0 sentinel
            fns += _S_FUNCTION.pack(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
            continue
        ps = list(fn["parm_size"]) + [0] * (8 - len(fn["parm_size"]))
        fns += _S_FUNCTION.pack(fn["first_statement"], fn["parm_start"],
                                fn["locals"], 0, fn["s_name"], fn["s_file"],
                                fn["numparms"], *ps[:8])
    ofs_functions = emit(fns)

    gdef = bytearray()
    for (t, o, s) in globaldefs:
        gdef += _S_DEF.pack(t & 0xffff, o & 0xffff, s)
    ofs_globaldefs = emit(gdef)

    fdef = bytearray()
    for (t, o, s) in fielddefs:
        fdef += _S_DEF.pack(t & 0xffff, o & 0xffff, s)
    ofs_fielddefs = emit(fdef)

    globs = bytearray()
    for i in range(state.numpr_globals):
        globs += struct.pack("<i", state.gi(i))
    ofs_globals = emit(globs)

    _S_HEADER.pack_into(
        header, 0,
        PROG_VERSION, crc,
        ofs_statements, len(state.statements),
        ofs_globaldefs, len(globaldefs),
        ofs_fielddefs, len(fielddefs),
        ofs_functions, len(state.functions),
        ofs_strings, len(strings),
        ofs_globals, state.numpr_globals,
        state.size_fields)
    return b"".join(bytes(p) for p in parts)
